# for MOTChallenge-Like dir structure 
# ${data_root}:
#    |
#    |___${train_folder_name}(Optional)
#          |
#          |____${seq_name}
#                     |_______${image_folder}
#                                    |____${frame_name}
#                     |_______${gt_folder_name}
#                                    |____${gt_txt_name}
#    |___${test_folder_name}(Optional)
#          |
#          |____${seq_name}
#                     |_______${image_folder}
#                                    |____${frame_name}
#                     |_______${gt_folder_name}   
#                                    |____${gt_txt_name}


# track result MUST OBEY this strcture:
# result:
#    |
#    |_____${train or test}(Optional)
#                  |
#                  |_____${tracker_name}(Optional)
#                                |_______ ${seq_name}.txt


gt_structure_config: 
  data_root: '/data/wujiapeng/datasets/DanceTrack/'
  has_split: True
  train_or_test: test
  train_folder_name: train
  test_folder_name: val
  gt_folder_name: gt
  gt_txt_name: 'gt.txt'  # gt.txt, {seq_name}.txt, etc.
  gt_loc_format: '{data_root}/{split_name}/{seq_name}/{gt_folder_name}/{gt_txt_name}' 

tracker_structure_config:
  trackers_folder: './result/dancetrack_MambaTrack/val'
  has_split: False
  split_name: ''
  has_tracker_name: False
  trackers_to_eval:   # None for all


# other options
OUTPUT_FOLDER: './track_eval_output'   # Where to save eval results (if None  same as TRACKERS_FOLDER)

SEQ_INFO:  # seq_name: seq_length
  dancetrack0005: 1203
  dancetrack0077: 1203
  dancetrack0073: 703
  dancetrack0065: 702
  dancetrack0035: 703
  dancetrack0047: 1203
  dancetrack0079: 1202
  dancetrack0058: 1601
  dancetrack0081: 984
  dancetrack0030: 1263
  dancetrack0014: 1203
  dancetrack0094: 603
  dancetrack0010: 1203
  dancetrack0026: 302
  dancetrack0019: 2402
  dancetrack0063: 1000
  dancetrack0090: 1004
  dancetrack0004: 1203
  dancetrack0034: 923
  dancetrack0007: 1203
  dancetrack0097: 1203
  dancetrack0025: 803
  dancetrack0043: 183
  dancetrack0041: 1003
  dancetrack0018: 503

# CLASS configs
CLASS_NAME_TO_CLASS_ID:
  'valid': 1


CLASSES_TO_EVAL: 
  - 'valid'

DISTRACTOR_CLASSES_NAMES:


# whether to set as single-class evaluation, if set true, then all tracking results are considered as single class
AS_SINGLE_CLASS:
  'enabled': true
  'single_class_id': -1

# zero mark, crowd (i.e. ignored region), occlusion and truncation settings
# the predicted bounding box in this region or situation can be omitted to get a reasonable results

ZERO_MARK:  # in gt annotation, the 'score' column (idx 6) indicates whether to consider the bbox
  'enabled': false  # if is 0, then dropped the gt bbox

CROWD_IGNORE_REGION:
  'enabled': false
  'col_idx': 7  # in Visdrone the class (col 7 in annotation) 0 indicates the ignored region
  'class_id': 
    - '0'  # list format. and the class is str type (because the txt is read as str)

TRUNCATION: # indicates the degree of object parts appears outside a frame
  'enabled': false  # whether filter the high-trunction objects
  'thresh': 0  # when > 0, ommited

OCCLUSION:  # indicates the fraction of objects being occluded
  'enabled': false  # whether filter the high-trunction objects
  'thresh': 1  # when > 1, ommited

COL_IDX_MAP:  # in gt file and tracking results file, the meaning of each cols. key: info, value: col idx
  'time': 0
  'id': 1 
  'bbox_start': 2
  'bbox_end': 5
  'score': 6
  'class': 7
  'visibility': 8

FRAME_START_IDX: 1  # in a seq, the first frame is frame 0 or frame 1 

# python scripts/run_custom_dataset.py --config_path configs/DanceTrack.yaml
