# for MOTChallenge-Like dir structure 
# ${data_root}:
#    |
#    |___${train_folder_name}(Optional)
#          |
#          |____${seq_name}
#                     |_______${image_folder}
#                                    |____${frame_name}
#                     |_______${gt_folder_name}
#                                    |____${gt_txt_name}
#    |___${test_folder_name}(Optional)
#          |
#          |____${seq_name}
#                     |_______${image_folder}
#                                    |____${frame_name}
#                     |_______${gt_folder_name}   
#                                    |____${gt_txt_name}


# track result MUST OBEY this strcture:
# result:
#    |
#    |_____${train or test}(Optional)
#                  |
#                  |_____${tracker_name}(Optional)
#                                |_______ ${seq_name}.txt


gt_structure_config: 
  data_root: '/data/wujiapeng/datasets/MOT17/'
  has_split: True
  train_or_test: train
  train_folder_name: train
  test_folder_name: test
  gt_folder_name: gt
  gt_txt_name: 'gt.txt'  # gt.txt, {seq_name}.txt, etc.
  gt_loc_format: '{data_root}/{split_name}/{seq_name}/{gt_folder_name}/{gt_txt_name}' 

tracker_structure_config:
  trackers_folder: './result/mot17_ocsort/train'
  has_split: False
  split_name: ''
  has_tracker_name: False
  trackers_to_eval:   # None for all


# other options
OUTPUT_FOLDER: './track_eval_output'   # Where to save eval results (if None  same as TRACKERS_FOLDER)

SEQ_INFO:  # seq_name: seq_length
  # 'MOT17-02-DPM': 600
  # 'MOT17-02-FRCNN': 600
  'MOT17-02-SDP': 600
  # 'MOT17-04-DPM': 1050
  # 'MOT17-04-FRCNN': 1050
  'MOT17-04-SDP': 1050
  # 'MOT17-05-DPM': 837
  # 'MOT17-05-FRCNN': 837
  'MOT17-05-SDP': 837
  # 'MOT17-09-DPM': 525
  # 'MOT17-09-FRCNN': 525
  'MOT17-09-SDP': 525
  # 'MOT17-10-DPM': 654
  # 'MOT17-10-FRCNN': 654
  'MOT17-10-SDP': 654
  # 'MOT17-11-DPM': 900
  # 'MOT17-11-FRCNN': 900
  'MOT17-11-SDP': 900
  # 'MOT17-13-DPM': 750
  # 'MOT17-13-FRCNN': 750
  'MOT17-13-SDP': 750

# CLASS configs
CLASS_NAME_TO_CLASS_ID:
  'pedestrian': 1
  'person_on_vehicle': 2
  'car': 3
  'bicycle': 4
  'motorbike': 5
  'non_mot_vehicle': 6
  'static_person': 7
  'distractor': 8
  'occluder': 9
  'occluder_on_ground': 10
  'occluder_full': 11
  'reflection': 12
  'crowd': 13


CLASSES_TO_EVAL: 
  - 'pedestrian'

DISTRACTOR_CLASSES_NAMES:
  - 'person_on_vehicle'
  - 'static_person'
  - 'distractor'
  - 'reflection'


# whether to set as single-class evaluation, if set true, then all tracking results are considered as single class
AS_SINGLE_CLASS:
  'enabled': true
  'single_class_id': -1

# zero mark, crowd (i.e. ignored region), occlusion and truncation settings
# the predicted bounding box in this region or situation can be omitted to get a reasonable results

ZERO_MARK:  # in gt annotation, the 'score' column (idx 6) indicates whether to consider the bbox
  'enabled': true  # if is 0, then dropped the gt bbox

CROWD_IGNORE_REGION:
  'enabled': false
  'col_idx': 7  # in Visdrone the class (col 7 in annotation) 0 indicates the ignored region
  'class_id': 
    - '0'  # list format. and the class is str type (because the txt is read as str)

TRUNCATION: # indicates the degree of object parts appears outside a frame
  'enabled': false  # whether filter the high-trunction objects
  'thresh': 0  # when > 0, ommited

OCCLUSION:  # indicates the fraction of objects being occluded
  'enabled': false  # whether filter the high-trunction objects
  'thresh': 1  # when > 1, ommited

COL_IDX_MAP:  # in gt file and tracking results file, the meaning of each cols. key: info, value: col idx
  'time': 0
  'id': 1 
  'bbox_start': 2
  'bbox_end': 5
  'score': 6
  'class': 7
  'visibility': 8

FRAME_START_IDX: 1  # in a seq, the first frame is frame 0 or frame 1 

# python scripts/run_custom_dataset.py --config_path configs/MOT17_train.yaml
