# for YOLO-Like dir structure 
# ${data_root}:
#    |
#    |___${train_folder_name}(Optional)
#          |
#          |____${seq_folder_name}
#          |          |_______${seq_name}
#          |                         |____${frame_name}
#          |____${gt_folder_name}
#                     |____${gt_txt_name}
#    |___${test_folder_name}(Optional)
#          |
#          |____${seq_folder_name}
#          |          |_______${seq_name}
#          |                         |____${frame_name}
#          |____${gt_folder_name}
#                     |____${gt_txt_name}

# track result MUST OBEY this strcture:
# result:
#    |
#    |_____${train or test}(Optional)
#                  |
#                  |_____${tracker_name}(Optional)
#                                |_______ ${seq_name}.txt



gt_structure_config: 
  data_root: '/data/wujiapeng/datasets/VisDrone2019/VisDrone2019/'
  has_split: True
  train_or_test: test
  train_folder_name: merge_cls_gt_val
  test_folder_name: merge_cls_gt_val
  gt_folder_name: annotations
  gt_txt_name: '{seq_name}.txt'  # gt.txt, {seq_name}.txt, etc.
  gt_loc_format: '{data_root}/{split_name}/{gt_folder_name}/{gt_txt_name}' 

tracker_structure_config:
  trackers_folder: './result/history/qdtrack/qdtrack_yolox_visdrone_val_12epochs'
  has_split: False
  split_name: ''
  has_tracker_name: False
  trackers_to_eval:   # None for all


# other options
OUTPUT_FOLDER: './track_eval_output'   # Where to save eval results (if None  same as TRACKERS_FOLDER)

SEQ_INFO:  # seq_name: seq_length
  'uav0000086_00000_v': 464
  'uav0000117_02622_v': 349
  'uav0000137_00458_v': 233
  'uav0000182_00000_v': 363
  'uav0000268_05773_v': 978
  'uav0000305_00000_v': 184
  'uav0000339_00001_v': 275

# CLASS configs
CLASS_NAME_TO_CLASS_ID:
  'ignored regions': 0
  'valid': -1
  'people': 2
  'others': 3

CLASSES_TO_EVAL: 
  - 'valid'

DISTRACTOR_CLASSES_NAMES:
  - 'people'
  - 'others'

# whether to set as single-class evaluation, if set true, then all tracking results are considered as single class
AS_SINGLE_CLASS:
  'enabled': true
  'single_class_id': -1

# whether to set as single-class evaluation, if set true, then all tracking results are considered as single class
AS_SINGLE_CLASS:
  'enabled': false
  'single_class_id': -1

# zero mark, crowd (i.e. ignored region), occlusion and truncation settings
# the predicted bounding box in this region or situation can be omitted to get a reasonable results

ZERO_MARK:  # in gt annotation, the 'score' column (idx 6) indicates whether to consider the bbox
  'enabled': true  # if is 0, then dropped the gt bbox

CROWD_IGNORE_REGION:
  'enabled': true
  'col_idx': 7  # in Visdrone the class (col 7 in annotation) 0 indicates the ignored region
  'class_id': 
    - '0'  # list format. and the class is str type (because the txt is read as str)

TRUNCATION: # indicates the degree of object parts appears outside a frame. in VisDrone, no truncation = 0 (truncation ratio 0%), and partial truncation = 1 (truncation ratio 1% ~ 50%)
  'enabled': true  # whether filter the high-trunction objects
  'thresh': 0  # when > 0, ommited

OCCLUSION:  # indicates the fraction of objects being occluded. in VisDrone, no occlusion = 0 (occlusion ratio 0%), partial occlusion = 1 (occlusion ratio 1% ~ 50%), 
  # heavy occlusion = 2 (occlusion ratio 50% ~ 100%))
  'enabled': true  # whether filter the high-trunction objects
  'thresh': 1  # when > 1, ommited

COL_IDX_MAP:  # in gt file and tracking results file, the meaning of each cols. key: info, value: col idx
  'time': 0
  'id': 1 
  'bbox_start': 2
  'bbox_end': 5
  'score': 6
  'class': 7
  'truncation': 8
  'occlusion': 9

FRAME_START_IDX: 1  # in a seq, the first frame is frame 0 or frame 1 
  
# python scripts/run_custom_dataset.py --config_path configs/VisDrone_val_merge_class.yaml
